// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_v_tpNzTifWA42oK3mL82JOiHFmnGmco',
    appId: '1:616451049757:android:f5d70ad4ef3a415dd7b9f4',
    messagingSenderId: '616451049757',
    projectId: 'cohesive-memory-342803',
    databaseURL: 'https://cohesive-memory-342803-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cohesive-memory-342803.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkPb3mqlBEDfh9KHH_TEBRLI95knnrZfY',
    appId: '1:616451049757:ios:96772be2357a9187d7b9f4',
    messagingSenderId: '616451049757',
    projectId: 'cohesive-memory-342803',
    databaseURL: 'https://cohesive-memory-342803-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cohesive-memory-342803.appspot.com',
    iosClientId: '616451049757-stf5ppsrvn5u1hocdflsckujrjrukk05.apps.googleusercontent.com',
    iosBundleId: 'com.example.recommendationDsp',
  );
}
